### ISSUE TITLE
Make the page mobile responsive

### ISSUE THREAD

**Issue by Blankscreen-exe** [Blankscreen-exe/ColorToGrayScale-converter#7]
The title and the dark theme button needs to be aligned.

For now on mobile screen it looks like this:
![image](https://github.com/user-attachments/assets/a2807e3c-3998-470b-bf5a-b3cdbf226d6a)

**Comment by maxmartinn** [comment]
I can pick up this issue I have experience with mobile webdesign

**Comment by Blankscreen-exe** [comment]
Thanks. I am waiting for your PR

**Comment by Blankscreen-exe** [comment]
This was done by @kyracho in pull request #9.
